name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-chengdu.aliyuncs.com
        username: maxinfan2009
        password: Wamcd24!
        logout: true

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/hslr/sun-panel:1.4.0 docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/sun-panel:1.4.0
         #skopeo copy docker://apache/skywalking-java-agent:8.16.0-java11 docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/skywalking-java-agent:8.16.0-java11
         #skopeo copy docker://docker.io/acryldata/datahub-upgrade:head docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/datahub-upgrade:head
         #skopeo copy docker://docker.io/acryldata/datahub-ingestion:head docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/acryldata/datahub-ingestion:head
         #skopeo copy docker://docker.io/acryldata/acryl-datahub-mysql-setup:head docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/acryl-datahub-mysql-setup:head
         #skopeo copy docker://docker.io/amazon/aws-lambda-nodejs:14 docker:/registry.cn-chengdu.aliyuncs.com/matthew_k8s/amazon/aws-lambda-nodejs:14
         skopeo copy docker://docker.io/node:18.20.5-alpine3.20 docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/node:18.20.5-alpine3.20
         skopeo copy docker://docker.io/node:16-alpine docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/node:16-alpine
         skopeo copy docker://docker.io/nginx:1.27.3-alpine docker://registry.cn-chengdu.aliyuncs.com/matthew_k8s/nginx:1.27.3-alpine 
      
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中
